# Site settings
title: BLOG ISYANATION
header-img: img/home-bg.jpg
email: nfiarts@gmail.com
copyright_name: ISYANATION
description: "Semua aktifitas, update, jadwal manggung tebaru Isyana Sarasvati akan di posting disini"
baseurl: "/articles"
url: "https://www.isyanation.tk/articles"
twitter_username: isyanation
github_username:  isyanation
facebook_username:  nfiarts
email_username:  nfiarts@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
